### ISSUE TITLE
Can't place a second word after the first turn.

### ISSUE THREAD

**Issue by MohamedZalat** [MayukhGautam-C/3110_Scrabble_Proj#33]
> Welcome to Definitely Not Scrabble!
Enter your name:
moe
moe's score is: 0
 [ C  A  G  E  O  C  I ]
Enter your command:
place v 17 cage
        0 1 2 3 4 5 6 7 8 9
        _ _ _ _ _ _ _ _ _ _
0  | 0 0 0 0 0 0 0 0 0 0
1  | 0 0 0 0 0 0 0 C 0 0
2  | 0 0 0 0 0 0 0 A 0 0
3  | 0 0 0 0 0 0 0 G 0 0
4  | 0 0 0 0 0 0 0 E 0 0
5  | 0 0 0 0 0 0 0 0 0 0
6  | 0 0 0 0 0 0 0 0 0 0
7  | 0 0 0 0 0 0 0 0 0 0
8  | 0 0 0 0 0 0 0 0 0 0
9  | 0 0 0 0 0 0 0 0 0 0
moe's score is: 7
 [ O  C  I  B  P  U  P ]
Enter your command:
place h 26 cap
Invalid letter for the word
        0 1 2 3 4 5 6 7 8 9
        _ _ _ _ _ _ _ _ _ _
0  | 0 0 0 0 0 0 0 0 0 0
1  | 0 0 0 0 0 0 0 C 0 0
2  | 0 0 0 0 0 0 0 A 0 0
3  | 0 0 0 0 0 0 0 G 0 0
4  | 0 0 0 0 0 0 0 E 0 0
5  | 0 0 0 0 0 0 0 0 0 0
6  | 0 0 0 0 0 0 0 0 0 0
7  | 0 0 0 0 0 0 0 0 0 0
8  | 0 0 0 0 0 0 0 0 0 0
9  | 0 0 0 0 0 0 0 0 0 0
moe's score is: 7
 [ O  C  I  B  P  U  P ]
Enter your command:
place h 26 cap
Invalid letter for the word
        0 1 2 3 4 5 6 7 8 9
        _ _ _ _ _ _ _ _ _ _
0  | 0 0 0 0 0 0 0 0 0 0
1  | 0 0 0 0 0 0 0 C 0 0
2  | 0 0 0 0 0 0 0 A 0 0
3  | 0 0 0 0 0 0 0 G 0 0
4  | 0 0 0 0 0 0 0 E 0 0
5  | 0 0 0 0 0 0 0 0 0 0
6  | 0 0 0 0 0 0 0 0 0 0
7  | 0 0 0 0 0 0 0 0 0 0
8  | 0 0 0 0 0 0 0 0 0 0
9  | 0 0 0 0 0 0 0 0 0 0
moe's score is: 7
 [ O  C  I  B  P  U  P ]
Enter your command:
pass
        0 1 2 3 4 5 6 7 8 9
        _ _ _ _ _ _ _ _ _ _
0  | 0 0 0 0 0 0 0 0 0 0
1  | 0 0 0 0 0 0 0 C 0 0
2  | 0 0 0 0 0 0 0 A 0 0
3  | 0 0 0 0 0 0 0 G 0 0
4  | 0 0 0 0 0 0 0 E 0 0
5  | 0 0 0 0 0 0 0 0 0 0
6  | 0 0 0 0 0 0 0 0 0 0
7  | 0 0 0 0 0 0 0 0 0 0
8  | 0 0 0 0 0 0 0 0 0 0
9  | 0 0 0 0 0 0 0 0 0 0
moe's score is: 7
 [ O  C  I  B  P  U  P ]
Enter your command:
pass
        0 1 2 3 4 5 6 7 8 9
        _ _ _ _ _ _ _ _ _ _
0  | 0 0 0 0 0 0 0 0 0 0
1  | 0 0 0 0 0 0 0 C 0 0
2  | 0 0 0 0 0 0 0 A 0 0
3  | 0 0 0 0 0 0 0 G 0 0
4  | 0 0 0 0 0 0 0 E 0 0
5  | 0 0 0 0 0 0 0 0 0 0
6  | 0 0 0 0 0 0 0 0 0 0
7  | 0 0 0 0 0 0 0 0 0 0
8  | 0 0 0 0 0 0 0 0 0 0
9  | 0 0 0 0 0 0 0 0 0 0
moe's score is: 7
 [ O  C  I  B  P  U  P ]
Enter your command:
pass
        0 1 2 3 4 5 6 7 8 9
        _ _ _ _ _ _ _ _ _ _
0  | 0 0 0 0 0 0 0 0 0 0
1  | 0 0 0 0 0 0 0 C 0 0
2  | 0 0 0 0 0 0 0 A 0 0
3  | 0 0 0 0 0 0 0 G 0 0
4  | 0 0 0 0 0 0 0 E 0 0
5  | 0 0 0 0 0 0 0 0 0 0
6  | 0 0 0 0 0 0 0 0 0 0
7  | 0 0 0 0 0 0 0 0 0 0
8  | 0 0 0 0 0 0 0 0 0 0
9  | 0 0 0 0 0 0 0 0 0 0
moe's score is: 7
 [ O  C  I  B  P  U  P ]
Enter your command:
place v 17 pup
Invalid placement or word
        0 1 2 3 4 5 6 7 8 9
        _ _ _ _ _ _ _ _ _ _
0  | 0 0 0 0 0 0 0 0 0 0
1  | 0 0 0 0 0 0 0 C 0 0
2  | 0 0 0 0 0 0 0 A 0 0
3  | 0 0 0 0 0 0 0 G 0 0
4  | 0 0 0 0 0 0 0 E 0 0
5  | 0 0 0 0 0 0 0 0 0 0
6  | 0 0 0 0 0 0 0 0 0 0
7  | 0 0 0 0 0 0 0 0 0 0
8  | 0 0 0 0 0 0 0 0 0 0
9  | 0 0 0 0 0 0 0 0 0 0
moe's score is: 7
 [ O  C  I  B  P  U  P ]
Enter your command:
place v 18 pup
Invalid placement or word
        0 1 2 3 4 5 6 7 8 9
        _ _ _ _ _ _ _ _ _ _
0  | 0 0 0 0 0 0 0 0 0 0
1  | 0 0 0 0 0 0 0 C 0 0
2  | 0 0 0 0 0 0 0 A 0 0
3  | 0 0 0 0 0 0 0 G 0 0
4  | 0 0 0 0 0 0 0 E 0 0
5  | 0 0 0 0 0 0 0 0 0 0
6  | 0 0 0 0 0 0 0 0 0 0
7  | 0 0 0 0 0 0 0 0 0 0
8  | 0 0 0 0 0 0 0 0 0 0
9  | 0 0 0 0 0 0 0 0 0 0
moe's score is: 7
 [ O  C  I  B  P  U  P ]
Enter your command:
place v 18 pub
Invalid placement or word
        0 1 2 3 4 5 6 7 8 9
        _ _ _ _ _ _ _ _ _ _
0  | 0 0 0 0 0 0 0 0 0 0
1  | 0 0 0 0 0 0 0 C 0 0
2  | 0 0 0 0 0 0 0 A 0 0
3  | 0 0 0 0 0 0 0 G 0 0
4  | 0 0 0 0 0 0 0 E 0 0
5  | 0 0 0 0 0 0 0 0 0 0
6  | 0 0 0 0 0 0 0 0 0 0
7  | 0 0 0 0 0 0 0 0 0 0
8  | 0 0 0 0 0 0 0 0 0 0
9  | 0 0 0 0 0 0 0 0 0 0
moe's score is: 7
 [ O  C  I  B  P  U  P ]
Enter your command:
place h 56 pub
Invalid placement or word
        0 1 2 3 4 5 6 7 8 9
        _ _ _ _ _ _ _ _ _ _
0  | 0 0 0 0 0 0 0 0 0 0
1  | 0 0 0 0 0 0 0 C 0 0
2  | 0 0 0 0 0 0 0 A 0 0
3  | 0 0 0 0 0 0 0 G 0 0
4  | 0 0 0 0 0 0 0 E 0 0
5  | 0 0 0 0 0 0 0 0 0 0
6  | 0 0 0 0 0 0 0 0 0 0
7  | 0 0 0 0 0 0 0 0 0 0
8  | 0 0 0 0 0 0 0 0 0 0
9  | 0 0 0 0 0 0 0 0 0 0
moe's score is: 7
 [ O  C  I  B  P  U  P ]
Enter your command:
place h 55 pub
Invalid Command
        0 1 2 3 4 5 6 7 8 9
        _ _ _ _ _ _ _ _ _ _
0  | 0 0 0 0 0 0 0 0 0 0
1  | 0 0 0 0 0 0 0 C 0 0
2  | 0 0 0 0 0 0 0 A 0 0
3  | 0 0 0 0 0 0 0 G 0 0
4  | 0 0 0 0 0 0 0 E 0 0
5  | 0 0 0 0 0 0 0 0 0 0
6  | 0 0 0 0 0 0 0 0 0 0
7  | 0 0 0 0 0 0 0 0 0 0
8  | 0 0 0 0 0 0 0 0 0 0
9  | 0 0 0 0 0 0 0 0 0 0
moe's score is: 7
 [ O  C  I  B  P  U  P ]
Enter your command:
place h 07 pub
Invalid placement or word
        0 1 2 3 4 5 6 7 8 9
        _ _ _ _ _ _ _ _ _ _
0  | 0 0 0 0 0 0 0 0 0 0
1  | 0 0 0 0 0 0 0 C 0 0
2  | 0 0 0 0 0 0 0 A 0 0
3  | 0 0 0 0 0 0 0 G 0 0
4  | 0 0 0 0 0 0 0 E 0 0
5  | 0 0 0 0 0 0 0 0 0 0
6  | 0 0 0 0 0 0 0 0 0 0
7  | 0 0 0 0 0 0 0 0 0 0
8  | 0 0 0 0 0 0 0 0 0 0
9  | 0 0 0 0 0 0 0 0 0 0
moe's score is: 7
 [ O  C  I  B  P  U  P ]
Enter your command:
place h 70 pub
Invalid placement or word
        0 1 2 3 4 5 6 7 8 9
        _ _ _ _ _ _ _ _ _ _
0  | 0 0 0 0 0 0 0 0 0 0
1  | 0 0 0 0 0 0 0 C 0 0
2  | 0 0 0 0 0 0 0 A 0 0
3  | 0 0 0 0 0 0 0 G 0 0
4  | 0 0 0 0 0 0 0 E 0 0
5  | 0 0 0 0 0 0 0 0 0 0
6  | 0 0 0 0 0 0 0 0 0 0
7  | 0 0 0 0 0 0 0 0 0 0
8  | 0 0 0 0 0 0 0 0 0 0
9  | 0 0 0 0 0 0 0 0 0 0
moe's score is: 7
 [ O  C  I  B  P  U  P ]
Enter your command:
swap ci
        0 1 2 3 4 5 6 7 8 9
        _ _ _ _ _ _ _ _ _ _
0  | 0 0 0 0 0 0 0 0 0 0
1  | 0 0 0 0 0 0 0 C 0 0
2  | 0 0 0 0 0 0 0 A 0 0
3  | 0 0 0 0 0 0 0 G 0 0
4  | 0 0 0 0 0 0 0 E 0 0
5  | 0 0 0 0 0 0 0 0 0 0
6  | 0 0 0 0 0 0 0 0 0 0
7  | 0 0 0 0 0 0 0 0 0 0
8  | 0 0 0 0 0 0 0 0 0 0
9  | 0 0 0 0 0 0 0 0 0 0
moe's score is: 7
 [ O  B  P  U  P  X  N ]
Enter your command:
place v 18 pun
Invalid placement or word
        0 1 2 3 4 5 6 7 8 9
        _ _ _ _ _ _ _ _ _ _
0  | 0 0 0 0 0 0 0 0 0 0
1  | 0 0 0 0 0 0 0 C 0 0
2  | 0 0 0 0 0 0 0 A 0 0
3  | 0 0 0 0 0 0 0 G 0 0
4  | 0 0 0 0 0 0 0 E 0 0
5  | 0 0 0 0 0 0 0 0 0 0
6  | 0 0 0 0 0 0 0 0 0 0
7  | 0 0 0 0 0 0 0 0 0 0
8  | 0 0 0 0 0 0 0 0 0 0
9  | 0 0 0 0 0 0 0 0 0 0
moe's score is: 7
 [ O  B  P  U  P  X  N ]
Enter your command:

**Comment by MayukhGautam-C** [comment]
The way we had this setup was to type the word with the letters missing. For instance, when CAGE was on the board, typing place h 26 cp would work. We forgot to mention this in the readme
